//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by todayitem.rc
//
#define IDS_APPNAME                     1
#define IDI_DISPLAYICON                 2
#define IDS_TAB0                        110
#define IDS_TAB1                        111
#define IDS_TAB2                        112
#define IDS_TAB3                        113
#define IDS_TAB4                        114
#define IDS_TAB5                        115
#define IDS_TAB6                        116
#define IDS_TAB7                        117
#define IDS_TAB8                        118
#define IDS_TAB9                        119
#define IDS_TAB10                       120
#define IDD_DIALOGDUMMY                 500
#define IDD_MENU_ICON                   501
#define IDD_MENU_HEADER                 502
#define IDD_DIALOGPAGE0                 510
#define IDD_DIALOGPAGE1                 511
#define IDD_DIALOGPAGE2                 512
#define IDD_DIALOGPAGE3                 513
#define IDD_DIALOGPAGE4                 514
#define IDD_DIALOGPAGE5                 515
#define IDD_DIALOGPAGE6                 516
#define IDD_DIALOGPAGE7                 517
#define IDD_DIALOGPAGE8                 518
#define IDD_DIALOGPAGE9                 519
#define IDD_DIALOGPAGE10                520
#define IDC_MICON_SCREEN                1001
#define IDC_MICON_NAME                  1002
#define IDC_MICON_IMAGE                 1003
#define IDC_MICON_SOUND                 1004
#define IDC_MICON_EXEC                  1005
#define IDC_MICON_PARAMETERS            1006
#define IDC_MICON_EXECALT               1007
#define IDC_MICON_PARAMETERSALT         1008
#define IDC_MICON_TYPE                  1009
#define IDC_MICON_ICON                  1011
#define IDC_MICON_SPIN_SCREEN           1012
#define IDC_MICON_SPIN_ICON             1013
#define IDC_MICON_IMAGE_B               1015
#define IDC_MICON_EXECALT_B             1016
#define IDC_MICON_EXEC_B                1017
#define IDC_MICON_LAUNCHANIMATION       1018
#define IDC_MICON_SOUND_B               1019
#define IDC_EDIT_CS_ICON_WIDTH          1032
#define IDC_EDIT_CS_ICONS_PER_ROW       1033
#define IDC_EDIT_CS_TEXT_HEIGHT         1034
#define IDC_EDIT_CS_TEXT_OFFSET         1035
#define IDC_EDIT_CS_TEXT_COLOR          1036
#define IDC_BUTTON_CS_TEXT_COLOR        1037
#define IDC_CHECK_CS_TEXT_BOLD          1038
#define IDC_EDIT_CS_BACK_COLOR1         1039
#define IDC_BUTTON_CS_BACK_COLOR1       1040
#define IDC_EDIT_CS_BACK_COLOR2         1041
#define IDC_BUTTON_CS_BACK_COLOR2       1042
#define IDC_EDIT_CS_MINHSPACE           1043
#define IDC_EDIT_CS_ADDVSPACE           1044
#define IDC_EDIT_CS_OFFSET_LEFT         1045
#define IDC_EDIT_CS_OFFSET_TOP          1046
#define IDC_EDIT_CS_OFFSET_RIGHT        1047
#define IDC_EDIT_CS_OFFSET_BOTTOM       1048
#define IDC_EDIT_HEADER_HEIGHT          1066
#define IDC_EDIT_HEADER_COLOR           1067
#define IDC_EDIT_HEADER_WEIGHT          1068
#define IDC_EDIT_HEADER_OFFSET          1069
#define IDC_EDIT_CIRCLES_DIAMETER       1070
#define IDC_EDIT_CIRCLES_DISTANCE       1071
#define IDC_EDIT_BUBBLE_NOTIF           1072
#define IDC_EDIT_BUBBLE_STATE           1073
#define IDC_EDIT_BUBBLE_ALARM           1074
#define IDC_EDIT_MOVE_THRESHOLD         1075
#define IDC_EDIT_MOVE_FACTOR            1076
#define IDC_EDIT_MIN_VELOCITY           1077
#define IDC_EDIT_MAX_VELOCITY           1078
#define IDC_CHECK_VERTICAL_SCROLL       1079
#define IDC_EDIT_SIS_HEIGHT             1080
#define IDC_EDIT_SIS_WIDTH              1081
#define IDC_EDIT_SIS_WEIGHT             1082
#define IDC_EDIT_SIS_COLOR              1083
#define IDC_BUTTON_SIS_COLOR            1084
#define IDC_COMBO_SIS                   1085
#define IDC_EDIT_SIS_OFFSET_LEFT        1086
#define IDC_EDIT_SIS_OFFSET_TOP         1087
#define IDC_EDIT_SIS_OFFSET_RIGHT       1088
#define IDC_EDIT_SIS_OFFSET_BOTTOM      1089
#define IDC_CHECK_CLOCK_FORMAT12        1095
#define IDC_EDIT_BACK_WALLPAPER         1096
#define IDC_BUTTON_BACK_WALLPAPER       1097
#define IDC_CHECK_BACK_STATIC           1098
#define IDC_CHECK_BACK_TRANSPARENT      1099
#define IDC_EDIT_BACK_COLOR             1100
#define IDC_BUTTON_BACK_COLOR           1101
#define IDC_CHECK_FULLSCREEN            1102
#define IDC_CHECK_NEVER_SHOW_TASKBAR    1103
#define IDC_CHECK_DISABLE_RIGHT_CLICK   1104
#define IDC_CHECK_IGNORE_ROTATION       1105
#define IDC_CHECK_ONLAUNCH_CLOSE        1106
#define IDC_CHECK_ONLAUNCH_ANIMATE      1107
#define IDC_EDIT_ONLAUNCH_VIBRATE       1108
#define IDC_EDIT_NOTIFY_TIMER           1109
#define IDC_BUTTON_BUBBLE_NOTIF         1110
#define IDC_BUTTON_BUBBLE_STATE         1111
#define IDC_BUTTON_BUBBLE_ALARM         1112
#define IDC_BUTTON_HEADER_COLOR         1113
#define IDC_CHECK_NO_WINDOW_TITLE       1114
#define IDC_EDIT_HEADER                 1115
#define IDC_EDIT_CIRCLES_OFFSET         1116
#define IDC_STATICAPPVER                1117
#define IDC_STATICURL                   1118
#define IDC_CHECK_FREESTYLE_SCROLL      1124
#define IDC_EDIT_BACK_FACTOR            1142
#define IDC_COMBO_CS                    1144
#define IDC_CHECK_ONLAUNCH_SOUND        1145
#define IDC_BUTTON_ANIM_COLOR           1146
#define IDC_EDIT_ANIM_COLOR             1147
#define IDC_EDIT_WAV                    1148
#define IDC_BUTTON_WAV                  1149
#define IDC_BUTTON_WAV_PLAY             1150
#define IDC_EDIT_HEIGHTP                1151
#define IDC_EDIT_HEIGHTL                1152
#define IDC_EDIT_OUTOFSCREEN_LEFT       1153
#define IDC_BUTTON_OUTOFSCREEN_LEFT     1154
#define IDC_EDIT_OUTOFSCREEN_RIGHT      1155
#define IDC_BUTTON_OUTOFSCREEN_RIGHT    1156
#define IDC_EDIT_OUTOFSCREEN_TOP        1157
#define IDC_BUTTON_OUTOFSCREEN_TOP      1158
#define IDC_EDIT_OUTOFSCREEN_BOTTOM     1159
#define IDC_BUTTON_OUTOFSCREEN_BOTTOM   1160
#define IDC_CHECK_TRANS_ALPHABLEND      1161
#define IDC_CHECK_TRANS_ALPHAONBLACK    1162
#define IDC_EDIT_TRANS_THRESHOLD        1163
#define IDC_CHECK_TRANS_BMP             1164
#define IDC_BUTTON_RESET_SETTINGS       1165
#define IDC_EDIT_PRESSED_ICON           1166
#define IDC_BUTTON_PRESSED_ICON         1167
#define IDC_EDIT_PRESSED_SOUND          1168
#define IDC_BUTTON_PRESSED_SOUND        1169
#define IDC_BUTTON_PRESSED_SOUND_PLAY   1170
#define IDC_EDIT_REFRESH_TIME           1171

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1172
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
