//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by todayitem.rc
//
#define IDS_APPNAME                     1
#define IDD_MENU_ICON                   102
#define IDR_ACCELERATORS                107
#define IDS_TAB0                        109
#define IDS_TAB1                        110
#define IDS_TAB2                        111
#define IDS_TAB3                        112
#define IDS_TAB4                        113
#define IDS_TAB5                        114
#define IDS_TAB6                        115
#define IDI_DISPLAYICON                 116
#define IDD_MENU_HEADER                 120
#define IDD_DIALOGDUMMY                 500
#define IDD_DIALOGPAGE0                 510
#define IDD_DIALOGPAGE1                 511
#define IDD_DIALOGPAGE2                 512
#define IDD_DIALOGPAGE3                 513
#define IDD_DIALOGPAGE4                 514
#define IDD_DIALOGPAGE5                 515
#define IDD_DIALOGPAGE6                 516
#define IDC_MICON_SCREEN                1001
#define IDC_MICON_NAME                  1002
#define IDC_MICON_IMAGE                 1003
#define IDC_MICON_SOUND                 1004
#define IDC_MICON_EXEC                  1005
#define IDC_MICON_PARAMETERS            1006
#define IDC_MICON_EXECALT               1007
#define IDC_MICON_PARAMETERSALT         1008
#define IDC_MICON_TYPE                  1009
#define IDC_MICON_ICON                  1011
#define IDC_MICON_SPIN_SCREEN           1012
#define IDC_MICON_SPIN_ICON             1013
#define IDC_MICON_IMAGE_B               1015
#define IDC_MICON_EXECALT_B             1016
#define IDC_MICON_EXEC_B                1017
#define IDC_MICON_LAUNCHANIMATION       1018
#define IDC_MICON_SOUND_B               1019
#define IDC_EDIT_MS_ICON_WIDTH          1032
#define IDC_EDIT_MS_ICONS_PER_ROW       1033
#define IDC_EDIT_MS_TEXT_HEIGHT         1034
#define IDC_EDIT_MS_TEXT_OFFSET         1035
#define IDC_EDIT_MS_TEXT_COLOR          1036
#define IDC_BUTTON_MS_TEXT_COLOR        1037
#define IDC_CHECK_MS_TEXT_BOLD          1038
#define IDC_EDIT_MS_BACK_COLOR1         1039
#define IDC_BUTTON_MS_BACK_COLOR1       1040
#define IDC_EDIT_MS_BACK_COLOR2         1041
#define IDC_BUTTON_MS_BACK_COLOR2       1042
#define IDC_EDIT_MS_MINHSPACE           1043
#define IDC_EDIT_MS_ADDVSPACE           1044
#define IDC_EDIT_MS_OFFSET_LEFT         1045
#define IDC_EDIT_MS_OFFSET_TOP          1046
#define IDC_EDIT_MS_OFFSET_RIGHT        1047
#define IDC_EDIT_MS_OFFSET_BOTTOM       1048
#define IDC_EDIT_BB_ICON_WIDTH          1049
#define IDC_EDIT_BB_ICONS_PER_ROW       1050
#define IDC_EDIT_BB_TEXT_HEIGHT         1051
#define IDC_EDIT_BB_TEXT_OFFSET         1052
#define IDC_EDIT_BB_TEXT_COLOR          1053
#define IDC_BUTTON_BB_TEXT_COLOR        1054
#define IDC_CHECK_BB_TEXT_BOLD          1055
#define IDC_EDIT_BB_BACK_COLOR1         1056
#define IDC_BUTTON_BB_BACK_COLOR1       1057
#define IDC_EDIT_BB_BACK_COLOR2         1058
#define IDC_BUTTON_BB_BACK_COLOR2       1059
#define IDC_EDIT_BB_MINHSPACE           1060
#define IDC_EDIT_BB_ADDVSPACE           1061
#define IDC_EDIT_BB_OFFSET_LEFT         1062
#define IDC_EDIT_BB_OFFSET_TOP          1063
#define IDC_EDIT_BB_OFFSET_RIGHT        1064
#define IDC_EDIT_BB_OFFSET_BOTTOM       1065
#define IDC_EDIT_HEADER_HEIGHT          1066
#define IDC_EDIT_HEADER_COLOR           1067
#define IDC_EDIT_HEADER_WEIGHT          1068
#define IDC_EDIT_HEADER_OFFSET          1069
#define IDC_EDIT_CIRCLES_DIAMETER       1070
#define IDC_EDIT_CIRCLES_DISTANCE       1071
#define IDC_EDIT_BUBBLE_NOTIF           1072
#define IDC_EDIT_BUBBLE_STATE           1073
#define IDC_EDIT_BUBBLE_ALARM           1074
#define IDC_EDIT_MOVE_THRESHOLD         1075
#define IDC_EDIT_MOVE_FACTOR            1076
#define IDC_EDIT_MIN_VELOCITY           1077
#define IDC_EDIT_MAX_VELOCITY           1078
#define IDC_CHECK_VERTICAL_SCROLL       1079
#define IDC_EDIT_DOW_HEIGHT             1080
#define IDC_EDIT_DOW_WIDTH              1081
#define IDC_EDIT_DOW_WEIGHT             1082
#define IDC_EDIT_DOW_COLOR              1083
#define IDC_BUTTON_DOW_COLOR            1084
#define IDC_EDIT_DOM_HEIGHT             1085
#define IDC_EDIT_DOM_WIDTH              1086
#define IDC_EDIT_DOM_WEIGHT             1087
#define IDC_EDIT_DOM_COLOR              1088
#define IDC_BUTTON_DOM_COLOR            1089
#define IDC_EDIT_CLOCK_HEIGHT           1090
#define IDC_EDIT_CLOCK_WIDTH            1091
#define IDC_EDIT_CLOCK_WEIGHT           1092
#define IDC_EDIT_CLOCK_COLOR            1093
#define IDC_BUTTON_CLOCK_COLOR          1094
#define IDC_CHECK_CLOCK_FORMAT12        1095
#define IDC_EDIT_BACK_WALLPAPER         1096
#define IDC_BUTTON_BACK_WALLPAPER       1097
#define IDC_CHECK_BACK_STATIC           1098
#define IDC_CHECK_BACK_TRANSPARENT      1099
#define IDC_EDIT_BACK_COLOR             1100
#define IDC_BUTTON_BACK_COLOR           1101
#define IDC_CHECK_FULLSCREEN            1102
#define IDC_CHECK_NEVER_SHOW_TASKBAR    1103
#define IDC_CHECK_DISABLE_RIGHT_CLICK   1104
#define IDC_CHECK_IGNORE_ROTATION       1105
#define IDC_CHECK_ONLAUNCH_CLOSE        1106
#define IDC_CHECK_ONLAUNCH_ANIMATE      1107
#define IDC_EDIT_ONLAUNCH_VIBRATE       1108
#define IDC_EDIT_NOTIFY_TIMER           1109
#define IDC_BUTTON_BUBBLE_NOTIF         1110
#define IDC_BUTTON_BUBBLE_STATE         1111
#define IDC_BUTTON_BUBBLE_ALARM         1112
#define IDC_BUTTON_HEADER_COLOR         1113
#define IDC_CHECK_NO_WINDOW_TITLE       1114
#define IDC_EDIT_HEADER                 1115

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         40003
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
